title: My ML Blog
description: Aniket Lachyankar's Blog for Discussing ML topics
theme: just-the-docs

url: https://alachyan-ml.github.io/ml-blog

#aux_links:
#  Template Repository: https://github.com/just-the-docs/just-the-docs-template
